/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileencryption;

import javax.swing.JFileChooser;

/**
 *
 * @author missa
 */
public class InterfazBlow extends javax.swing.JFrame {
    String rsafileinputdir,rsadecryptfileinputdir, aesfileinputdir, aesdecryptfileinputdir, bffileinputdir, bfdecryptfileinputdir;

    /**
     * Creates new form InterfazBlow
     */
    public InterfazBlow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectInputBrowseBtnBF = new javax.swing.JButton();
        selectInputFileTxtBF = new javax.swing.JTextField();
        keyLabelBF = new javax.swing.JLabel();
        newFilenameLabelBF = new javax.swing.JLabel();
        outputFileTxtBF = new javax.swing.JTextField();
        encryptBtnBF = new javax.swing.JButton();
        keyTxtBF = new javax.swing.JTextField();
        selectInputBrowseBtnBF_dec = new javax.swing.JButton();
        selectInputFileTxtBF_dec = new javax.swing.JTextField();
        keyLabelBF_dec = new javax.swing.JLabel();
        keyTxtBF_dec = new javax.swing.JTextField();
        outputFileTxtBF_dec = new javax.swing.JTextField();
        newFilenameLabelBF_dec = new javax.swing.JLabel();
        encryptBtnBF_dec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectInputBrowseBtnBF.setText("Browse");
        selectInputBrowseBtnBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInputBrowseBtnBFActionPerformed(evt);
            }
        });

        keyLabelBF.setText("KEY: ");

        newFilenameLabelBF.setText("NEW FILENAME :");

        encryptBtnBF.setText("ENCRYPT");
        encryptBtnBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptBtnBFActionPerformed(evt);
            }
        });

        selectInputBrowseBtnBF_dec.setText("Browse");
        selectInputBrowseBtnBF_dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInputBrowseBtnBF_decActionPerformed(evt);
            }
        });

        keyLabelBF_dec.setText("KEY : ");

        newFilenameLabelBF_dec.setText("NEW FILENAME :");

        encryptBtnBF_dec.setText("DECRYPT");
        encryptBtnBF_dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptBtnBF_decActionPerformed(evt);
            }
        });

        jLabel1.setText("Cifrado mediante BLOWFISH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(newFilenameLabelBF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(outputFileTxtBF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(keyLabelBF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(keyTxtBF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(selectInputFileTxtBF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(selectInputBrowseBtnBF)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(encryptBtnBF_dec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(selectInputFileTxtBF_dec)
                                    .addGap(18, 18, 18)
                                    .addComponent(selectInputBrowseBtnBF_dec))
                                .addComponent(encryptBtnBF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(keyLabelBF_dec)
                                        .addComponent(newFilenameLabelBF_dec))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(keyTxtBF_dec, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(outputFileTxtBF_dec))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectInputBrowseBtnBF)
                    .addComponent(selectInputFileTxtBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLabelBF)
                    .addComponent(keyTxtBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFilenameLabelBF)
                    .addComponent(outputFileTxtBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(encryptBtnBF)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectInputBrowseBtnBF_dec)
                    .addComponent(selectInputFileTxtBF_dec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLabelBF_dec)
                    .addComponent(keyTxtBF_dec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileTxtBF_dec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newFilenameLabelBF_dec))
                .addGap(18, 18, 18)
                .addComponent(encryptBtnBF_dec)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectInputBrowseBtnBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInputBrowseBtnBFActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
                // Demonstrate "Open" dialog:
                int rVal = c.showOpenDialog(this);
                if (rVal == JFileChooser.APPROVE_OPTION) {
                    selectInputFileTxtBF.setText(c.getSelectedFile().getAbsolutePath());
                    bffileinputdir = c.getCurrentDirectory().toString();
                    outputFileTxtBF.setText("Encriptado_"+c.getSelectedFile().getName());
                }
    }//GEN-LAST:event_selectInputBrowseBtnBFActionPerformed

    private void encryptBtnBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptBtnBFActionPerformed
        // TODO add your handling code here:
        MainBFActivity mbf = new MainBFActivity();
            String fileinputdir, fileoutputdir, key;
            fileinputdir = selectInputFileTxtBF.getText();
            fileoutputdir = bffileinputdir+"/"+outputFileTxtBF.getText();
            key = keyTxtBF.getText();
            mbf.setInputdir(fileinputdir);
            mbf.setOutputdir(fileoutputdir);
            mbf.setKey(key);
            mbf.doEncryptBFA();
            //System.out.println(fileinputdir);
           // System.out.println(fileoutputdir);
           // System.out.println(key);
    }//GEN-LAST:event_encryptBtnBFActionPerformed

    private void selectInputBrowseBtnBF_decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInputBrowseBtnBF_decActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
            // Demonstrate "Open" dialog:
            int rVal = c.showOpenDialog(this);
            if (rVal == JFileChooser.APPROVE_OPTION) {
                selectInputFileTxtBF_dec.setText(c.getSelectedFile().getAbsolutePath());
                bfdecryptfileinputdir = c.getCurrentDirectory().toString();
                outputFileTxtBF_dec.setText("Decriptado_"+c.getSelectedFile().getName());
            }
    }//GEN-LAST:event_selectInputBrowseBtnBF_decActionPerformed

    private void encryptBtnBF_decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptBtnBF_decActionPerformed
        // TODO add your handling code here:
        MainBFActivity mbf = new MainBFActivity();
            String fileinputdir, fileoutputdir, key;
            fileinputdir = selectInputFileTxtBF_dec.getText();
            fileoutputdir = bfdecryptfileinputdir+"/"+outputFileTxtBF_dec.getText();
            key = keyTxtBF_dec.getText();
            mbf.setInputdir(fileinputdir);
            mbf.setOutputdir(fileoutputdir);
            mbf.setKey(key);
            mbf.doDecryptBFA();
            //System.out.println(fileinputdir);
           // System.out.println(fileoutputdir);
            //System.out.println(key);
    }//GEN-LAST:event_encryptBtnBF_decActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBlow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBlow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBlow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBlow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBlow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encryptBtnBF;
    private javax.swing.JButton encryptBtnBF_dec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel keyLabelBF;
    private javax.swing.JLabel keyLabelBF_dec;
    private javax.swing.JTextField keyTxtBF;
    private javax.swing.JTextField keyTxtBF_dec;
    private javax.swing.JLabel newFilenameLabelBF;
    private javax.swing.JLabel newFilenameLabelBF_dec;
    private javax.swing.JTextField outputFileTxtBF;
    private javax.swing.JTextField outputFileTxtBF_dec;
    private javax.swing.JButton selectInputBrowseBtnBF;
    private javax.swing.JButton selectInputBrowseBtnBF_dec;
    private javax.swing.JTextField selectInputFileTxtBF;
    private javax.swing.JTextField selectInputFileTxtBF_dec;
    // End of variables declaration//GEN-END:variables
}
